// Daily Digest — page interactions
// Auto-generated by GitHub Actions. Do not edit manually.
var GH_OWNER = "shelliwhite";
var GH_REPO  = "daily-digest";
var GH_PAT   = "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";
var SAVED_FILE = 'saved.json';

function toggleExpand(evt, cid) {
  evt.preventDefault();
  var btn = evt.target;
  var preview = document.getElementById(cid + '-preview');
  var full = document.getElementById(cid + '-full');
  if (!full) return;
  var expanded = !full.hidden;
  full.hidden = expanded;
  if (preview) preview.style.display = expanded ? '' : 'none';
  btn.textContent = expanded ? 'Read more' : 'Collapse';
}

window.addEventListener('message', function(evt) {
  if (!evt.data || evt.data.type !== 'resize') return;
  var iframe = document.getElementById(evt.data.id + '-iframe');
  if (!iframe) return;
  iframe.style.minHeight = Math.min(evt.data.h + 16, 852) + 'px';
});

async function ghGetFile(path) {
  var resp = await fetch(
    'https://api.github.com/repos/' + GH_OWNER + '/' + GH_REPO + '/contents/' + path,
    { headers: { 'Authorization': 'token ' + GH_PAT, 'Accept': 'application/vnd.github.v3+json' } }
  );
  if (resp.status === 404) return { content: [], sha: null };
  if (!resp.ok) throw new Error('GitHub GET failed: ' + resp.status);
  var data = await resp.json();
  var content = JSON.parse(atob(data.content.replace(/
/g, '')));
  return { content: content, sha: data.sha };
}

async function ghPutFile(path, content, sha, message) {
  var body = {
    message: message,
    content: btoa(unescape(encodeURIComponent(JSON.stringify(content, null, 2)))),
  };
  if (sha) body.sha = sha;
  var resp = await fetch(
    'https://api.github.com/repos/' + GH_OWNER + '/' + GH_REPO + '/contents/' + path,
    {
      method: 'PUT',
      headers: { 'Authorization': 'token ' + GH_PAT, 'Accept': 'application/vnd.github.v3+json', 'Content-Type': 'application/json' },
      body: JSON.stringify(body),
    }
  );
  if (!resp.ok) throw new Error('GitHub PUT failed: ' + resp.status);
}

async function saveForLater(evt, btn) {
  evt.preventDefault();
  btn.disabled = true;
  btn.textContent = 'Saving...';
  try {
    var entry = JSON.parse(btn.getAttribute('data-entry'));
    entry.saved_at = new Date().toISOString();
    var file = await ghGetFile(SAVED_FILE);
    var items = file.content;
    if (items.some(function(i) { return i.link === entry.link; })) {
      btn.textContent = 'Saved';
      return;
    }
    items.push(entry);
    await ghPutFile(SAVED_FILE, items, file.sha, 'Save: ' + entry.title.substring(0, 60));
    btn.textContent = 'Saved ✓';
  } catch(e) {
    console.error(e);
    btn.disabled = false;
    btn.textContent = 'Save failed';
  }
}

async function removeSaved(evt, btn) {
  evt.preventDefault();
  btn.disabled = true;
  btn.textContent = 'Removing...';
  try {
    var link = btn.getAttribute('data-link');
    var file = await ghGetFile(SAVED_FILE);
    var items = file.content.filter(function(i) { return i.link !== link; });
    await ghPutFile(SAVED_FILE, items, file.sha, 'Remove saved item');
    var card = btn.closest('.card');
    if (card) card.style.opacity = '0.4';
    btn.textContent = 'Removed';
  } catch(e) {
    console.error(e);
    btn.disabled = false;
    btn.textContent = 'Remove failed';
  }
}
